In [1]:
import numpy as np

In [2]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
np.array(((1, 2, 3), (4, 5, 6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros(10) + np.ones(10) + np.arange(10, 0, -1) - 1

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [6]:
np.random.randn(3, 4)

array([[-0.78961317,  0.6414664 ,  1.81642022,  1.22578156],
       [-1.62272942, -0.65138554, -0.05565175, -0.22449293],
       [-0.90002926, -1.56195812,  1.34196519, -0.34623587]])

In [7]:
np.random.rand(12).reshape(3, 4)

array([[0.46086004, 0.01289002, 0.33651813, 0.61566605],
       [0.04840823, 0.61163637, 0.5293969 , 0.32617925],
       [0.54207253, 0.79167234, 0.73666918, 0.57042949]])

In [8]:
np.mean(np.random.randn(1000000))

0.0014202389939255086

In [9]:
np.std(np.random.randn(1000000))

1.0010602474182067