In [1]:
import numpy as np
np.random.seed(98765)

In [2]:
arr1 = np.arange(5, 10)

print(arr1)
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)

arr1[0:3] = 0
print(arr1)

[5 6 7 8 9]
1
(5,)
int64
[0 0 0 8 9]


In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
np.array(((1, 2, 3), (4, 5, 6)))

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.zeros(10) + np.ones(10) + np.arange(10, 0, -1) - 1

array([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.])

In [6]:
np.random.randn(3, 4)

array([[-0.6504417 ,  0.85034195,  1.0750099 , -1.79416571],
       [ 0.9378183 , -0.75541276,  0.71758629,  1.02050263],
       [ 0.96599959, -0.04178252, -0.06769879,  0.80568588]])

In [7]:
np.random.rand(12).reshape(3, 4)

array([[0.79113127, 0.27496235, 0.58493699, 0.27509728],
       [0.52817509, 0.72574116, 0.64882384, 0.95133298],
       [0.56060354, 0.66623899, 0.36475457, 0.72420426]])

In [8]:
np.mean(np.random.randn(1000000))

0.0004852266173761474

In [9]:
np.std(np.random.randn(1000000))

0.9996945027901621

In [10]:
np.random.randn(3, 3) < np.zeros(shape=(3, 3))

array([[ True, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [11]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("source", "\n", arr2)
print("[0,0]", "\n", arr2[0,0])
print("[0,2]", "\n", arr2[0,2])
print("[2,0]", "\n", arr2[2,0])
print("[1:,:]", "\n", arr2[:1,:])
print("[:,:1]", "\n", arr2[:,:1])
print("[:2,1:]", "\n", arr2[:2,1:])

source 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[0,0] 
 1
[0,2] 
 3
[2,0] 
 7
[1:,:] 
 [[1 2 3]]
[:,:1] 
 [[1]
 [4]
 [7]]
[:2,1:] 
 [[2 3]
 [5 6]]
